name: hubx
description: Test Case
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  async: ^2.13.0
  auto_route: ^10.1.0+1
  bloc: ^9.0.0
  dio: ^5.9.0
  encrypt_shared_preferences: ^0.9.10
  firebase_analytics: ^11.4.5
  firebase_core: ^3.13.0

  firebase_crashlytics: ^4.3.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.5
  reactive_forms: ^18.1.1
  retrofit: ^4.7.1
  rxdart: ^0.28.0
  slang_flutter: ^4.8.0
  talker_flutter: ^4.9.3

dev_dependencies:
  auto_route_generator: ^10.0.1
  bloc_test: ^10.0.0
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.11.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  retrofit_generator: ^9.7.0
  slang_build_runner: ^4.8.0
  very_good_analysis: ^9.0.0

flutter_gen:
  # Optional
  integrations:
    image: true
    flutter_svg: true
    rive: false
    lottie: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/onboarding/page1/
    - assets/images/onboarding/page2/
    - assets/images/onboarding/page3/
